name: Scripter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  duplicate:
    name: Copy Script
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: hashspace
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Main
          path: scoop_main
      - name: Push New Registers
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          if !git diff --exit-code; then
              git add scoop_main/scripts
              git commit -m "update scripts"
              git push
          fi
