name: Scripter

on:
  workflow_dispatch:
  push:
    branches: 'master'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  duplicate:
    name: Copy Script
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: hashspace
      - name: Checkout Scoop
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Main
          path: scoop
      - name: Push New Registers
        shell: bash
        working-directory: hashspace
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          cp -rf ../scoop/scripts/{7-zip,git,python} scripts
          git add -A
          git commit -m "update scripts"
          git push
