name: Scripter

on:
  workflow_dispatch:
  push:
    branches: 'master'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  duplicate:
    name: Copy Script
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
        with:
          fetch-depth: 2
          path: hashcat
      - name: Checkout Main
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Main
          path: main
      - name: Checkout Extras
        uses: actions/checkout@main
        with:
          repository: ScoopInstaller/Extras
          path: extras
      - name: Push New Registers
        shell: bash
        working-directory: hashcat
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          cp -rf ../main/scripts/{7-zip,git,python} scripts
          cp -rf ../extras/scripts/{vscode} scripts
          git add -A
          git diff-index --quiet HEAD || git commit -m "update scripts"
          git push
