name: Updater

on:
  workflow_dispatch:
  push:
    branches: 'master'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  excavate:
    name: App Update
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
      - name: Update Manifests
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
